"""
Unit tests for NeMo Colang Generator.

Tests the ColangGenerator and related models for generating
Colang 2.x flow definitions from configuration.
"""

import pytest
from pathlib import Path
from tempfile import NamedTemporaryFile

from neo_guardrail_hub.providers.nemo import (
    ColangGenerator,
    ColangConfig,
    InputRailConfig,
    OutputRailConfig,
    TopicalRailConfig,
    generate_colang_from_dict,
)


class TestColangConfig:
    """Tests for ColangConfig model."""
    
    def test_default_config(self):
        """Test creating a default config with no rails."""
        config = ColangConfig()
        
        assert config.input_rails is None
        assert config.output_rails is None
        assert config.topical_rails is None
        assert config.refusal_message is None
        
    def test_input_rails_config(self):
        """Test input rails configuration."""
        config = ColangConfig(
            input_rails=InputRailConfig(
                self_check_input=True
            )
        )
        
        assert config.input_rails.self_check_input is True
        
    def test_output_rails_config(self):
        """Test output rails configuration."""
        config = ColangConfig(
            output_rails=OutputRailConfig(
                self_check_output=True,
                self_check_facts=True,
                self_check_hallucination=True
            )
        )
        
        assert config.output_rails.self_check_output is True
        assert config.output_rails.self_check_facts is True
        assert config.output_rails.self_check_hallucination is True
        
    def test_topical_rails_config(self):
        """Test topical rails configuration."""
        config = ColangConfig(
            topical_rails=TopicalRailConfig(
                allowed_topics=["customer_support", "products"],
                disallowed_topics=["politics", "religion"],
                allow_only_listed_topics=True
            )
        )
        
        assert config.topical_rails.allowed_topics == ["customer_support", "products"]
        assert config.topical_rails.disallowed_topics == ["politics", "religion"]
        assert config.topical_rails.allow_only_listed_topics is True


class TestColangGenerator:
    """Tests for ColangGenerator."""
    
    def test_generate_empty_config(self):
        """Test generating Colang with empty config."""
        config = ColangConfig()
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        # Should have header and imports
        assert "Auto-generated by Neo Guardrail Hub" in result
        assert "import core" in result
        assert "import llm" in result
        
    def test_generate_self_check_input(self):
        """Test generating self_check_input flow."""
        config = ColangConfig(
            input_rails=InputRailConfig(self_check_input=True)
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow self check input" in result
        assert "execute self_check_input" in result
        assert "bot refuse to respond" in result
        
    def test_generate_self_check_output(self):
        """Test generating self_check_output flow."""
        config = ColangConfig(
            output_rails=OutputRailConfig(self_check_output=True)
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow self check output" in result
        assert "execute self_check_output" in result
        
    def test_generate_fact_check(self):
        """Test generating fact checking flow."""
        config = ColangConfig(
            output_rails=OutputRailConfig(self_check_facts=True)
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow self check facts" in result
        assert "execute self_check_facts" in result
        
    def test_generate_hallucination_check(self):
        """Test generating hallucination detection flow."""
        config = ColangConfig(
            output_rails=OutputRailConfig(self_check_hallucination=True)
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow self check hallucination" in result
        assert "execute self_check_hallucination" in result
        
    def test_generate_disallowed_topic(self):
        """Test generating disallowed topic flow."""
        config = ColangConfig(
            topical_rails=TopicalRailConfig(
                disallowed_topics=["politics"]
            )
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow block politics topic" in result
        assert "user ask about politics" in result
        assert "bot inform cannot discuss topic" in result
        
    def test_generate_topic_whitelist(self):
        """Test generating topic whitelist flow."""
        config = ColangConfig(
            topical_rails=TopicalRailConfig(
                allowed_topics=["support", "products"],
                allow_only_listed_topics=True
            )
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define flow enforce topic whitelist" in result
        assert "support" in result
        assert "products" in result
        
    def test_custom_refusal_message(self):
        """Test custom refusal message."""
        custom_message = "Sorry, I cannot help with that request."
        config = ColangConfig(
            refusal_message=custom_message
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert custom_message in result
        
    def test_custom_user_messages(self):
        """Test custom user message definitions."""
        config = ColangConfig(
            custom_user_messages={
                "ask pricing": ["How much does it cost?", "What's the price?"]
            }
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define user ask pricing" in result
        assert "How much does it cost?" in result
        
    def test_custom_bot_messages(self):
        """Test custom bot message definitions."""
        config = ColangConfig(
            custom_bot_messages={
                "welcome user": ["Hello! How can I help you today?"]
            }
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        assert "define bot welcome user" in result
        assert "Hello! How can I help you today?" in result
        
    def test_generate_to_file(self, tmp_path):
        """Test generating Colang to a file."""
        config = ColangConfig(
            input_rails=InputRailConfig(self_check_input=True)
        )
        generator = ColangGenerator(config)
        
        output_file = tmp_path / "rails" / "generated.co"
        generator.generate_to_file(output_file)
        
        assert output_file.exists()
        content = output_file.read_text()
        assert "define flow self check input" in content
        
    def test_full_configuration(self):
        """Test generating with a full configuration."""
        config = ColangConfig(
            input_rails=InputRailConfig(
                self_check_input=True
            ),
            output_rails=OutputRailConfig(
                self_check_output=True,
                self_check_facts=True,
                self_check_hallucination=True
            ),
            topical_rails=TopicalRailConfig(
                allowed_topics=["support"],
                disallowed_topics=["politics", "religion"]
            ),
            refusal_message="I'm sorry, I can't help with that."
        )
        generator = ColangGenerator(config)
        
        result = generator.generate()
        
        # Verify all components are present
        assert "define flow self check input" in result
        assert "define flow self check output" in result
        assert "define flow self check facts" in result
        assert "define flow self check hallucination" in result
        assert "define flow block politics topic" in result
        assert "define flow block religion topic" in result


class TestGenerateColangFromDict:
    """Tests for the convenience function."""
    
    def test_basic_dict_config(self):
        """Test generating from a dictionary configuration."""
        config_dict = {
            "input_rails": {
                "self_check_input": True
            },
            "output_rails": {
                "self_check_output": True
            }
        }
        
        result = generate_colang_from_dict(config_dict)
        
        assert "define flow self check input" in result
        assert "define flow self check output" in result
        
    def test_empty_dict_config(self):
        """Test generating from an empty dictionary."""
        result = generate_colang_from_dict({})
        
        assert "Auto-generated by Neo Guardrail Hub" in result
        assert "import core" in result
        
    def test_complex_dict_config(self):
        """Test generating from a complex dictionary."""
        config_dict = {
            "input_rails": {
                "self_check_input": True
            },
            "output_rails": {
                "self_check_output": True,
                "self_check_facts": True
            },
            "topical_rails": {
                "disallowed_topics": ["politics", "violence"]
            },
            "custom_user_messages": {
                "greeting": ["hi", "hello"]
            },
            "refusal_message": "Cannot do that."
        }
        
        result = generate_colang_from_dict(config_dict)
        
        assert "define flow self check input" in result
        assert "define flow self check facts" in result
        assert "block politics topic" in result
        assert "Cannot do that." in result
