"""
Colang 2.x Generator for Neo Guardrail Hub.

This module generates Colang flow definitions from simplified YAML configuration.
It maps Neo Guardrail Hub concepts to NeMo Guardrails Colang 2.x syntax.

Features:
- Generate input rail flows (e.g., self_check_input)
- Generate output rail flows (e.g., self_check_output, fact_checking)
- Generate dialog/topical rail flows (allowed/disallowed topics)
- Template-based generation with customization support
"""

from pathlib import Path
from typing import Any, Optional

from .base import BaseGenerator
from .models import ColangConfig, InputRailConfig, OutputRailConfig, TopicalRailConfig


class ColangGenerator(BaseGenerator):
    """
    Generates Colang 2.x flow definitions from configuration.
    
    This generator creates .co files that define:
    - User message canonical forms
    - Bot message canonical forms
    - Input/output rail flows
    - Dialog rail flows for topic control
    
    Example usage:
        >>> config = ColangConfig(
        ...     input_rails=InputRailConfig(self_check_input=True),
        ...     output_rails=OutputRailConfig(self_check_output=True),
        ... )
        >>> generator = ColangGenerator(config)
        >>> colang_content = generator.generate()
    """
    
    # Colang 2.x imports
    COLANG_IMPORTS = """import core
import llm
import rails
"""

    # Standard bot refusal message
    DEFAULT_REFUSAL_MESSAGE = "I'm sorry, I can't respond to that."
    
    def __init__(
        self,
        config: ColangConfig,
        custom_templates_path: Optional[Path] = None,
    ):
        """
        Initialize the Colang generator.
        
        Args:
            config: Configuration specifying which rails to generate
            custom_templates_path: Optional path to custom templates
        """
        self.config = config
        self._custom_templates_path = custom_templates_path
        
    def generate(self) -> str:
        """
        Generate complete Colang 2.x file content.
        
        Returns:
            String containing the complete .co file content
        """
        sections = [
            self._generate_header(),
            self.COLANG_IMPORTS,
            self._generate_user_messages(),
            self._generate_bot_messages(),
            self._generate_input_rails(),
            self._generate_output_rails(),
            self._generate_topical_rails(),
        ]
        
        # Filter empty sections and join with newlines
        return "\n\n".join(section for section in sections if section.strip())
    
    def generate_to_file(self, output_path: Path) -> None:
        """
        Generate Colang content and write to a file.
        
        Args:
            output_path: Path where the .co file should be written
        """
        content = self.generate()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
    
    # =========================================================================
    # Individual Rail File Generation Methods
    # These methods generate content for separate .co files in rails/ directory
    # =========================================================================
    
    def generate_input_rail_file(self) -> str:
        """Generate content for input.co file.
        
        Returns:
            Complete input.co file content with self_check_input flow
        """
        return '''# Self Check Input Flow
# Auto-generated by Neo Guardrail Hub
# Validates user input for jailbreak/prompt injection attempts
# Uses NeMo's self_check_input action

define flow self check input
  $allowed = execute self_check_input
  if not $allowed
    bot refuse to respond
    stop

define bot refuse to respond
  "I'm sorry, I can't respond to that."
'''

    def generate_output_rail_file(self) -> str:
        """Generate content for output.co file.
        
        Returns:
            Complete output.co file content with self_check_output flow
        """
        return '''# Self Check Output Flow
# Auto-generated by Neo Guardrail Hub
# Validates bot response for appropriateness and safety
# Uses NeMo's self_check_output action

define flow self check output
  $allowed = execute self_check_output
  if not $allowed
    bot refuse to respond
    stop

define bot refuse to respond
  "I'm sorry, I can't respond to that."
'''

    def generate_fact_check_rail_file(self) -> str:
        """Generate content for fact_check.co file.
        
        Returns:
            Complete fact_check.co file content with self_check_facts flow
        """
        return '''# Self Check Facts Flow
# Auto-generated by Neo Guardrail Hub
# Validates if bot response is grounded in provided evidence (relevant_chunks)
# Uses NeMo's self_check_facts action which returns an accuracy score

define flow self check facts
    $accuracy = execute self_check_facts
    if $accuracy < 0.5
        bot say "I cannot verify that information based on the available sources."
        stop
'''

    def generate_hallucination_rail_file(self) -> str:
        """Generate content for hallucination.co file.
        
        Returns:
            Complete hallucination.co file content with self_check_hallucination flow
        """
        return '''# Self Check Hallucination Flow
# Auto-generated by Neo Guardrail Hub
# Detects inconsistencies in bot response by comparing multiple LLM samples
# Uses NeMo's self_check_hallucination action which returns a boolean

define flow self check hallucination
  $hallucination = execute self_check_hallucination
  if $hallucination
    bot inform answer unknown
    stop

define bot inform answer unknown
    "I don't have enough information to answer that accurately."
'''

    def generate_dialog_rail_file(self) -> str:
        """Generate content for dialog.co file from topical configuration.
        
        Returns:
            Complete dialog.co file content with topic blocking flows,
            or empty string if no topics are configured
        """
        if not self.config.topical_rails or not self.config.topical_rails.enabled:
            return ""
        
        topical = self.config.topical_rails
        
        # If no topics configured (allowed, disallowed, or custom), return empty
        if (not topical.disallowed_topics and 
            not topical.custom_topics and 
            not (topical.allowed_topics and topical.allow_only_listed_topics)):
            return ""
        
        lines = [
            "# Dialog Rails - Topical control",
            "# Auto-generated by Neo Guardrail Hub",
            "# Keeps the bot on-topic by blocking off-topic discussions",
            "",
        ]
        
        user_messages = []
        bot_messages = []
        flows = []
        
        # Process topics from the topic library
        from ..topic_library import get_topic_by_name
        
        for topic_name in topical.disallowed_topics:
            topic = get_topic_by_name(topic_name)
            if topic:
                # User message definition with examples
                examples = topic.user_examples[:10]  # Limit to 10 examples
                examples_str = "\n  ".join(f'"{ex}"' for ex in examples)
                user_messages.append(f'''define user ask about {topic_name}
  {examples_str}''')
                
                # Bot refusal response
                bot_response = topic.bot_responses[0] if topic.bot_responses else topical.off_topic_response
                bot_messages.append(f'''define bot refuse {topic_name}
  "{bot_response}"''')
                
                # Blocking flow
                flows.append(f'''define flow block {topic_name} topic
  user ask about {topic_name}
  bot refuse {topic_name}
  stop''')
        
        # Process custom topics
        for topic_name, topic_def in topical.custom_topics.items():
            examples = topic_def.get("examples", [])
            response = topic_def.get("response", topical.off_topic_response)
            
            if examples:
                # User message definition
                examples_str = "\n  ".join(f'"{ex}"' for ex in examples)
                user_messages.append(f'''define user ask about {topic_name}
  {examples_str}''')
                
                # Bot refusal response
                bot_messages.append(f'''define bot refuse {topic_name}
  "{response}"''')
                
                # Blocking flow
                flows.append(f'''define flow block {topic_name} topic
  user ask about {topic_name}
  bot refuse {topic_name}
  stop''')
        
        # Generate whitelist enforcement flow if allow_only_listed_topics is True
        if topical.allow_only_listed_topics and topical.allowed_topics:
            # Create a flow that only allows listed topics
            allowed_list = ", ".join(topical.allowed_topics)
            flows.append(f'''define flow enforce topic whitelist
  """Only allow conversations about: {allowed_list}"""
  user ...
  $on_topic = execute check_if_on_topic(topics=[{', '.join(f'"{t}"' for t in topical.allowed_topics)}])
  
  if not $on_topic
    bot refuse off_topic
    stop''')
        
        # Add default off-topic refusal
        bot_messages.append(f'''define bot refuse off_topic
  "{topical.off_topic_response}"''')
        
        # Combine all sections
        if user_messages:
            lines.append("# " + "=" * 78)
            lines.append("# User Messages - Disallowed Topics")
            lines.append("# " + "=" * 78)
            lines.append("")
            lines.append("\n\n".join(user_messages))
            lines.append("")
        
        if bot_messages:
            lines.append("# " + "=" * 78)
            lines.append("# Bot Messages - Topic Refusals")
            lines.append("# " + "=" * 78)
            lines.append("")
            lines.append("\n\n".join(bot_messages))
            lines.append("")
        
        if flows:
            lines.append("# " + "=" * 78)
            lines.append("# Dialog Flows - Block Off-Topic Discussions")
            lines.append("# " + "=" * 78)
            lines.append("")
            lines.append("\n\n".join(flows))
        
        return "\n".join(lines)
    
    def generate_rails_to_directory(self, rails_dir: Path) -> list[str]:
        """Generate individual .co files to a rails directory.
        
        Creates separate .co files for each enabled rail type:
        - rails/input.co - if self_check_input enabled
        - rails/output.co - if self_check_output enabled
        - rails/fact_check.co - if self_check_facts enabled
        - rails/hallucination.co - if self_check_hallucination enabled
        - rails/dialog.co - if topical rails with topics configured
        
        Args:
            rails_dir: Directory to write the .co files
            
        Returns:
            List of generated file names
        """
        rails_dir.mkdir(parents=True, exist_ok=True)
        generated_files = []
        
        # Generate input.co if self_check_input is enabled
        if self.config.input_rails and self.config.input_rails.self_check_input:
            content = self.generate_input_rail_file()
            (rails_dir / "input.co").write_text(content)
            generated_files.append("input.co")
        
        # Generate output.co if self_check_output is enabled
        if self.config.output_rails and self.config.output_rails.self_check_output:
            content = self.generate_output_rail_file()
            (rails_dir / "output.co").write_text(content)
            generated_files.append("output.co")
        
        # Generate fact_check.co if self_check_facts is enabled
        if self.config.output_rails and self.config.output_rails.self_check_facts:
            content = self.generate_fact_check_rail_file()
            (rails_dir / "fact_check.co").write_text(content)
            generated_files.append("fact_check.co")
        
        # Generate hallucination.co if self_check_hallucination is enabled
        if self.config.output_rails and self.config.output_rails.self_check_hallucination:
            content = self.generate_hallucination_rail_file()
            (rails_dir / "hallucination.co").write_text(content)
            generated_files.append("hallucination.co")
        
        # Generate dialog.co if topical rails with topics are configured
        dialog_content = self.generate_dialog_rail_file()
        if dialog_content:
            (rails_dir / "dialog.co").write_text(dialog_content)
            generated_files.append("dialog.co")
        
        return generated_files
        
    def _generate_header(self) -> str:
        """Generate file header with metadata."""
        return '''# Auto-generated by Neo Guardrail Hub
# Colang 2.x flow definitions for NeMo Guardrails
# Do not edit manually - regenerate from configuration
'''
    
    def _generate_user_messages(self) -> str:
        """Generate user message canonical forms.
        
        Note: Topical/dialog user messages should be defined in user-provided
        Colang files, as they are use-case specific.
        """
        messages = []
        
        # Add custom user messages from config (if any)
        if self.config.custom_user_messages:
            for name, examples in self.config.custom_user_messages.items():
                messages.append(self._create_user_message(name, examples))
        
        return "\n\n".join(messages) if messages else ""
    
    def _create_user_message(self, name: str, examples: list[str]) -> str:
        """
        Create a user message definition.
        
        Args:
            name: Canonical name for the user intent
            examples: List of example utterances
            
        Returns:
            Colang user message definition
        """
        examples_str = "\n  ".join(f'"{ex}"' for ex in examples)
        return f'''define user {name}
  {examples_str}'''
    
    def _generate_bot_messages(self) -> str:
        """Generate bot message canonical forms."""
        messages = []
        
        # Standard refusal message
        refusal_msg = self.config.refusal_message or self.DEFAULT_REFUSAL_MESSAGE
        messages.append(f'''define bot refuse to respond
  "{refusal_msg}"''')
        
        # Topic-specific responses
        if self.config.topical_rails:
            topical = self.config.topical_rails
            
            # Disallowed topic refusal
            if topical.disallowed_topics:
                messages.append(f'''define bot inform cannot discuss topic
  "I'm not able to discuss that topic. Is there something else I can help with?"''')
        
        # Custom bot messages
        if self.config.custom_bot_messages:
            for name, responses in self.config.custom_bot_messages.items():
                responses_str = "\n  ".join(f'"{r}"' for r in responses)
                messages.append(f'''define bot {name}
  {responses_str}''')
        
        return "\n\n".join(messages)
    
    def _generate_input_rails(self) -> str:
        """Generate input rail flows."""
        if not self.config.input_rails:
            return ""
            
        input_config = self.config.input_rails
        flows = []
        
        # Self-check input (jailbreak/prompt injection detection)
        if input_config.self_check_input:
            flows.append(self._generate_self_check_input_flow())
            
        return "\n\n".join(flows)
    
    def _generate_self_check_input_flow(self) -> str:
        """Generate self_check_input flow for jailbreak detection."""
        return '''define flow self check input
  """Check if user input is safe."""
  $allowed = execute self_check_input
  
  if not $allowed
    bot refuse to respond
    stop'''
    
    def _generate_output_rails(self) -> str:
        """Generate output rail flows."""
        if not self.config.output_rails:
            return ""
            
        output_config = self.config.output_rails
        flows = []
        
        # Self-check output (toxicity, appropriateness)
        if output_config.self_check_output:
            flows.append(self._generate_self_check_output_flow())
        
        # Fact checking
        if output_config.self_check_facts:
            flows.append(self._generate_fact_check_flow())
            
        # Hallucination detection
        if output_config.self_check_hallucination:
            flows.append(self._generate_hallucination_check_flow())
        
        return "\n\n".join(flows)
    
    def _generate_self_check_output_flow(self) -> str:
        """Generate self_check_output flow for response validation."""
        return '''define flow self check output
  """Check if bot response is appropriate."""
  $allowed = execute self_check_output
  
  if not $allowed
    bot refuse to respond
    stop'''
    
    def _generate_fact_check_flow(self) -> str:
        """Generate fact checking flow using NeMo's self check facts.
        
        The flow executes self_check_facts which returns an accuracy score.
        If accuracy < 0.5, the response is considered not grounded.
        """
        return '''define flow self check facts
  """Verify factual accuracy of bot response against evidence."""
  $accuracy = execute self_check_facts
  
  if $accuracy < 0.5
    bot say "I cannot verify that information based on the available sources."
    stop'''
    
    def _generate_hallucination_check_flow(self) -> str:
        """Generate hallucination detection flow using NeMo's self check hallucination."""
        return '''define flow self check hallucination
  """Detect potential hallucinations in bot response."""
  $check_hallucination = True
  $hallucination = execute self_check_hallucination
  
  if $hallucination
    bot inform response may contain errors
    stop'''
    
    def _generate_topical_rails(self) -> str:
        """Generate topical/dialog rail flows.
        
        Generates dialog.co content with:
        - User message definitions for disallowed topics
        - Bot refusal messages
        - Blocking flows for each topic
        - Whitelist enforcement if allow_only_listed_topics is True
        """
        if not self.config.topical_rails or not self.config.topical_rails.enabled:
            return ""
        
        topical = self.config.topical_rails
        
        # If no topics configured (allowed, disallowed, or custom), return empty
        if (not topical.disallowed_topics and 
            not topical.custom_topics and 
            not (topical.allowed_topics and topical.allow_only_listed_topics)):
            return ""
        
        sections = []
        sections.append(self._generate_dialog_header())
        
        # Generate from topic library
        if topical.disallowed_topics:
            sections.append(self._generate_topic_library_rails(topical))
        
        # Generate custom topics
        if topical.custom_topics:
            sections.append(self._generate_custom_topic_rails(topical))
        
        # Generate whitelist enforcement
        if topical.allow_only_listed_topics and topical.allowed_topics:
            sections.append(self._generate_whitelist_flow(topical))
        
        return "\n\n".join(section for section in sections if section.strip())
    
    def _generate_dialog_header(self) -> str:
        """Generate header for dialog rails."""
        return '''# Dialog Rails - Topical control
# Auto-generated from configuration
# Keeps the bot on-topic by blocking off-topic discussions'''
    
    def _generate_topic_library_rails(self, topical: TopicalRailConfig) -> str:
        """Generate rails from topic library entries."""
        from ..topic_library import get_topic_by_name
        
        sections = []
        user_messages = []
        bot_messages = []
        flows = []
        
        for topic_name in topical.disallowed_topics:
            topic = get_topic_by_name(topic_name)
            if topic:
                # Generate user message definition
                examples = topic.user_examples[:10]  # Limit to 10 examples
                examples_str = "\n  ".join(f'"{ex}"' for ex in examples)
                user_messages.append(f'''define user ask about {topic_name}
  {examples_str}''')
                
                # Generate bot response
                bot_response = topic.bot_responses[0] if topic.bot_responses else topical.off_topic_response
                bot_messages.append(f'''define bot refuse {topic_name}
  "{bot_response}"''')
                
                # Generate blocking flow
                flows.append(f'''define flow block {topic_name} topic
  user ask about {topic_name}
  bot refuse {topic_name}
  stop''')
        
        if user_messages:
            sections.append("# User Messages - Disallowed Topics")
            sections.extend(user_messages)
        
        if bot_messages:
            sections.append("# Bot Responses - Topic Refusals")
            sections.extend(bot_messages)
        
        if flows:
            sections.append("# Blocking Flows")
            sections.extend(flows)
        
        return "\n\n".join(sections)
    
    def _generate_custom_topic_rails(self, topical: TopicalRailConfig) -> str:
        """Generate rails from custom topic definitions."""
        sections = []
        user_messages = []
        bot_messages = []
        flows = []
        
        for topic_name, topic_def in topical.custom_topics.items():
            examples = topic_def.get("examples", [])
            response = topic_def.get("response", topical.off_topic_response)
            
            if examples:
                # Generate user message definition
                examples_str = "\n  ".join(f'"{ex}"' for ex in examples)
                user_messages.append(f'''define user ask about {topic_name}
  {examples_str}''')
                
                # Generate bot response
                bot_messages.append(f'''define bot refuse {topic_name}
  "{response}"''')
                
                # Generate blocking flow
                flows.append(f'''define flow block {topic_name} topic
  user ask about {topic_name}
  bot refuse {topic_name}
  stop''')
        
        if user_messages:
            sections.append("# Custom Topics - User Messages")
            sections.extend(user_messages)
        
        if bot_messages:
            sections.append("# Custom Topics - Bot Responses")
            sections.extend(bot_messages)
        
        if flows:
            sections.append("# Custom Topics - Blocking Flows")
            sections.extend(flows)
        
        return "\n\n".join(sections)
    
    def _generate_whitelist_flow(self, topical: TopicalRailConfig) -> str:
        """Generate whitelist enforcement flow.
        
        When allow_only_listed_topics is True, this creates a flow
        that blocks any topic not in the allowed_topics list.
        """
        if not topical.allowed_topics:
            return ""
        
        allowed_list = ", ".join(topical.allowed_topics)
        topics_str = ", ".join(f'"{t}"' for t in topical.allowed_topics)
        
        return f'''# Topic Whitelist Enforcement
define flow enforce topic whitelist
  """Only allow conversations about: {allowed_list}"""
  user ...
  $on_topic = execute check_if_on_topic(topics=[{topics_str}])
  
  if not $on_topic
    bot refuse off_topic
    stop

define bot refuse off_topic
  "{topical.off_topic_response}"'''


def generate_colang_from_dict(config_dict: dict[str, Any]) -> str:
    """
    Convenience function to generate Colang from a dictionary configuration.
    
    Args:
        config_dict: Dictionary with configuration matching ColangConfig structure
        
    Returns:
        Generated Colang 2.x content
    """
    config = ColangConfig.model_validate(config_dict)
    generator = ColangGenerator(config)
    return generator.generate()
