"""
NeMo config.yml Generator.

This module generates NeMo Guardrails config.yml files from Neo Guardrail Hub
configuration. It handles:
- Model configuration
- Rails configuration (input, output, dialog flows)
- Preset merging
- Streaming configuration
"""

from pathlib import Path
from typing import Any, Optional

import yaml

from .base import BaseGenerator
from .models import NeMoGuardrailsConfig


class ConfigGenerator(BaseGenerator):
    """
    Generates NeMo config.yml from Neo Guardrail Hub configuration.
    
    The config.yml is the main configuration file for NeMo Guardrails,
    specifying which LLM to use and which rails/flows to enable.
    
    Example:
        >>> from .models import NeMoGuardrailsConfig, LLMConfig, ColangConfig
        >>> nemo_config = NeMoGuardrailsConfig(
        ...     llm=LLMConfig(engine="openai", model="gpt-4"),
        ...     enable_input_rails=True,
        ... )
        >>> generator = ConfigGenerator(nemo_config)
        >>> config_dict = generator.generate()
        >>> generator.write(Path("./nemo_config/config.yml"))
    """
    
    def __init__(
        self,
        nemo_config: NeMoGuardrailsConfig,
        presets_path: Optional[Path] = None,
    ):
        """
        Initialize the config generator.
        
        Args:
            nemo_config: Complete NeMo configuration
            presets_path: Optional path to presets directory
        """
        self.nemo_config = nemo_config
        self.presets_path = presets_path
        
    def generate(self) -> dict[str, Any]:
        """
        Generate NeMo config.yml content as dictionary.
        
        Returns:
            Dictionary ready to be serialized to YAML
        """
        config = {}
        
        # Generate models section
        config["models"] = self._generate_models_section()
        
        # Generate rails section
        rails_config = self._generate_rails_section()
        if rails_config:
            config["rails"] = rails_config
            
        # Add streaming if enabled
        if self.nemo_config.streaming:
            config["streaming"] = True
            
        return config
    
    def generate_yaml(self) -> str:
        """
        Generate config.yml content as YAML string.
        
        Returns:
            YAML-formatted configuration string
        """
        config = self.generate()
        
        lines = [
            "# Auto-generated by Neo Guardrail Hub",
            "# NeMo Guardrails configuration",
            "",
        ]
        
        # Create a custom YAML dumper that uses literal block scalars for multiline strings
        class LiteralDumper(yaml.SafeDumper):
            pass
        
        def literal_str_representer(dumper, data):
            """Use literal block scalar (|) for multiline strings."""
            if '\n' in data:
                return dumper.represent_scalar('tag:yaml.org,2002:str', data, style='|')
            return dumper.represent_scalar('tag:yaml.org,2002:str', data)
        
        LiteralDumper.add_representer(str, literal_str_representer)
        
        return "\n".join(lines) + yaml.dump(
            config,
            Dumper=LiteralDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
            width=float('inf'),  # Prevent line wrapping
        )
    
    def write(self, output_path: Path) -> None:
        """
        Write config.yml to file.
        
        Args:
            output_path: Path to output file (should end with config.yml)
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.generate_yaml())
        
    def _generate_models_section(self) -> list[dict[str, Any]]:
        """
        Generate the models section of config.yml.
        
        Returns:
            List of model configurations
        """
        llm = self.nemo_config.llm
        
        model_config = {
            "type": "main",
            "engine": llm.engine,
            "model": llm.model,
        }
        
        # Add temperature if non-default
        if llm.temperature != 0.0:
            model_config["temperature"] = llm.temperature
            
        # Add max_tokens if specified
        if llm.max_tokens:
            model_config["max_tokens"] = llm.max_tokens
            
        return [model_config]
    
    def _generate_rails_section(self) -> dict[str, Any]:
        """
        Generate the rails section of config.yml.
        
        Returns:
            Dictionary with input, output, and dialog rail configurations
        """
        rails_config = {}
        
        # Input rails
        if self.nemo_config.enable_input_rails:
            input_flows = self._get_input_flows()
            if input_flows:
                rails_config["input"] = {"flows": input_flows}
            
            # Add jailbreak detection config if enabled
            jailbreak_config = self._get_jailbreak_detection_config()
            if jailbreak_config:
                if "config" not in rails_config:
                    rails_config["config"] = {}
                rails_config["config"]["jailbreak_detection"] = jailbreak_config
        
        # Output rails
        if self.nemo_config.enable_output_rails:
            output_flows = self._get_output_flows()
            if output_flows:
                rails_config["output"] = {"flows": output_flows}
        
        # Dialog rails
        if self.nemo_config.enable_dialog_rails:
            dialog_config = self._get_dialog_flows()
            if dialog_config:
                rails_config["dialog"] = dialog_config
                
        return rails_config
    
    def _get_input_flows(self) -> list[str]:
        """Get list of input flow names to enable."""
        flows = []
        
        colang = self.nemo_config.colang
        if colang and colang.input_rails:
            # Add jailbreak detection heuristics FIRST (fast, no LLM calls)
            if colang.input_rails.jailbreak_detection_heuristics and colang.input_rails.jailbreak_detection_heuristics.enabled:
                flows.append("jailbreak detection heuristics")
            
            # Then add self_check_input (uses LLM)
            if colang.input_rails.self_check_input:
                flows.append("self check input")
                
        return flows
    
    def _get_jailbreak_detection_config(self) -> Optional[dict[str, Any]]:
        """Get jailbreak detection heuristics configuration."""
        colang = self.nemo_config.colang
        if not colang or not colang.input_rails:
            return None
        
        jailbreak = colang.input_rails.jailbreak_detection_heuristics
        if not jailbreak or not jailbreak.enabled:
            return None
        
        config = {
            "length_per_perplexity_threshold": jailbreak.length_per_perplexity_threshold,
            "prefix_suffix_perplexity_threshold": jailbreak.prefix_suffix_perplexity_threshold,
        }
        
        # Add server endpoint if configured (for production use)
        if jailbreak.server_endpoint:
            config["server_endpoint"] = jailbreak.server_endpoint
        
        return config
                
        return flows
    
    def _get_output_flows(self) -> list[str]:
        """Get list of output flow names to enable."""
        flows = []
        
        colang = self.nemo_config.colang
        if colang and colang.output_rails:
            output_rails = colang.output_rails
            
            if output_rails.self_check_output:
                flows.append("self check output")
            if output_rails.self_check_facts:
                flows.append("self check facts")
            if output_rails.self_check_hallucination:
                flows.append("self check hallucination")
                
        return flows
    
    def _get_dialog_flows(self) -> Optional[dict[str, Any]]:
        """
        Get dialog rails configuration.
        
        Returns:
            Dictionary with dialog rails settings or None if not enabled
        """
        colang = self.nemo_config.colang
        if not colang or not colang.topical_rails or not colang.topical_rails.enabled:
            return None
        
        # Return the dialog rails configuration
        # Users provide their own Colang files - we just enable the rails
        return {
            "single_call": {
                "enabled": True
            },
            "user_messages": {
                "embeddings_only": True
            }
        }
    
    def merge_with_preset(self, preset_name: str) -> dict[str, Any]:
        """
        Merge generated config with a preset.
        
        Args:
            preset_name: Name of the preset (e.g., "general", "financial")
            
        Returns:
            Merged configuration dictionary
        """
        if not self.presets_path:
            return self.generate()
            
        preset_path = self.presets_path / preset_name / "config.yml"
        if not preset_path.exists():
            return self.generate()
            
        # Load preset
        with open(preset_path) as f:
            preset_config = yaml.safe_load(f)
            
        # Generate base config
        generated_config = self.generate()
        
        # Deep merge: generated config takes precedence
        return self._deep_merge(preset_config, generated_config)
    
    def _deep_merge(
        self, 
        base: dict[str, Any], 
        override: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Deep merge two dictionaries, with override taking precedence.
        
        Args:
            base: Base dictionary
            override: Override dictionary (takes precedence)
            
        Returns:
            Merged dictionary
        """
        result = base.copy()
        
        for key, value in override.items():
            if key in result and isinstance(result[key], dict) and isinstance(value, dict):
                result[key] = self._deep_merge(result[key], value)
            else:
                result[key] = value
                
        return result
